# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-FindConcept
version:      0.01
version_from: FindConcept.pm
installdirs:  site
requires:
    WWW::Mechanize:                0.70

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
